### ISSUE TITLE
Move issue templates from GitLab to GitHub

### ISSUE THREAD

**Issue by jason-fox** [itti-pl/depalletization-agent-rose-ap#1]
- rename `.gitlab` folder to `.github` and follow https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository as necessary.

**Comment by tomasz-springer** [comment]
Gitlab repository remainings and hidden files removed. Thx.
