### ISSUE TITLE
Structure of the README does not align with RAMP Standard

### ISSUE THREAD

**Issue by jason-fox** [itti-pl/depalletization-agent-rose-ap#2]
- There is no `LICENSE` file at the root of the repo. Please add an Apache-2.0 licence and add your company name to the copyright in the file.
-  Amend the license badge to point to your license

e.g.

```md
[![License: Apache](https://img.shields.io/github/license/itti-pl/depalletization-agent-rose-ap.svg)](https://www.apache.org/licenses/LICENSE-2.0.html#redistribution)
```

- Ensure that the final section of the `README` explicitly repeats the information as shown: 

```md
## License

[Apache2.0](LICENSE) © 2021 <Company Name>
```

You can follow the example [here](https://github.com/ramp-eu/JS2SF)

-  Register on read the docs and re-add the `mkdocs.yml` and `.readthedocs.yml` files to generate the documentation. More info [here](https://www.mkdocs.org/#getting-started):

Sample files: [.readthedocs.yml](https://github.com/ramp-eu/TTE.project1/blob/master/.readthedocs.yml),  [mkdocs.yml](https://github.com/ramp-eu/TTE.project1/blob/master/mkdocs.yml) 

The documentation badge can then be re-added:

```md
[![Documentation Status](https://readthedocs.org/projects/****/badge/?version=latest)](https://****.readthedocs.io/en/latest/?badge=latest)
```

where `****` is the name of your readthedocs project.

**Comment by tomasz-springer** [comment]
License file added. License section/footer added. Readthedocks ready. Thx.

**Comment by jason-fox** [comment]
You could add a link to https://depalletization-agent-rose-ap.readthedocs.io/ in the info box here as well:

![Screenshot 2021-06-30 at 11 34 22](https://user-images.githubusercontent.com/3439249/123938219-33f64a00-d997-11eb-8e66-79d9ce68c50c.png)
