### ISSUE TITLE
Dockerfile not found

### ISSUE THREAD

**Issue by jason-fox** [itti-pl/depalletization-agent-rose-ap#3]
The Docker readme is currently a placeholder in Polish 🇵🇱  - please update to add more instructions **in English**. (This is a CII Best practices requirement - there is no problem having Polish as well)

The Dockerfile for the Agent does not exist - please add.

A good template based on multi-stage builds can be found [here](https://github.com/telefonicaid/iotagent-ul/tree/master/docker)

**Comment by tomasz-springer** [comment]
Done. Docker filer update. Language changes done. Thx.
